[package]
name = "eww-niri-workspaces"
version = "0.1.0"
edition = "2021"

[dependencies]
niri-ipc = { git = "https://github.com/YaLTeR/niri.git", tag = "v25.05.1" }
serde = "1.0.219"
serde_json = "1.0"
eyre = "0.6"
